on:
  workflow_dispatch:
    inputs:
      Samsung Galaxy S23 Ultra:
        type: boolean
      Samsung Galaxy S23:
        type: boolean
      Samsung Galaxy S22 Ultra:
        type: boolean
      Samsung Galaxy S22 Plus:
        type: boolean
      Samsung Galaxy S22:
        type: boolean
      Samsung Galaxy S21 Ultra:
        type: boolean
      Samsung Galaxy S21:
        type: boolean
      Samsung Galaxy M52:
        type: boolean
      # Samsung Galaxy M32:
      #   type: boolean
      # Google Pixel 9 Pro XL:
      #   type: boolean
      # Google Pixel 8 Pro:
      #   type: boolean
      # Google Pixel 8:
      #   type: boolean
      # Google Pixel 7 Pro:
      #   type: boolean
      # Google Pixel 7:
      #   type: boolean
      # iPhone 15 Pro Max:
      #   type: boolean
      # iPhone 15 Pro:
      #   type: boolean
      # iPhone 15 Plus:
      #   type: boolean
      # iPhone 15:
      #   type: boolean
      # iPhone 14 Pro Max:
      #   type: boolean
      # iPhone 14 Pro:
      #   type: boolean
      # iPhone 14 Plus:
      #   type: boolean
      # iPhone 14:
      #   type: boolean
      # iPhone 13 Pro Max:
      #   type: boolean
      # iPhone 13 Pro:
      #   type: boolean
      # iPhone 13 Mini:
      #   type: boolean
jobs:
  get-selected:
    name: Get Selected Checkboxes
    runs-on: ubuntu-latest
    outputs: # This needs to be set if you want to consume the output on another job
      selected: ${{ steps.get-selected-step.outputs.selected}}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Get Selected
        id: get-selected-step
        uses: joao-zanutto/get-selected@v1.1.1
        with:
          separator: ','
          format: 'list'

      - name: Consume on the same job
        run: echo ${{ steps.get-selected-step.outputs.selected }}

  consume-on-another-job:
    runs-on: ubuntu-latest
    name: Consume Output
    needs: get-selected
    steps:
      - name: Print
        run: echo ${{ needs.get-selected.outputs.selected }}
