name: Pylint

on:
  push:

  workflow_dispatch:
      inputs:
        name:
          type: string
          required: true
          description: "Name of the user"
jobs:
  build:
    name: Build in runner
    runs-on: maven11-runner-amd
