on:
  workflow_dispatch:
    inputs:
      option1:
        type: boolean
      option2:
        type: boolean
      option3:
        type: boolean
jobs:
  get-selected:
    name: Get Selected Checkboxes
    runs-on: ubuntu-latest
    outputs: # This needs to be set if you want to consume the output on another job
      selected: ${{ steps.get-selected-step.outputs.selected}}
    steps:
    - name: Example Interactive Inputs Step
      id: interactive-inputs
      uses: boasihq/interactive-inputs@v2
      with:
        ngrok-authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
        notifier-slack-enabled: "true"
        notifier-slack-channel: "# shopfront-automation-reports"
        notifier-slack-token: ${{ secrets.SLACK_TOKEN }}
        notifier-discord-enabled: "false"
        notifier-discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
        timeout: 160
        title: "A batch of 10 feature flags have been added to be deployed. Would you like to proceed?"
        interactive: |
          fields:
            - label: exclude-domains
              properties:
                description: Select the domains to exclude from the roll out
                display: Exclude domain(s)
                type: multiselect
                choices: 
                  ["Payments", "Bookings", "Notifications", "Support"]
            
    - name: Display Outputs
      shell: bash
      run: |
        echo "Display Outputs"
        echo -e "\n==============================\n"
        echo "Detected Outputs: ${{steps.interactive-inputs.outputs.exclude-domains}}"
        echo -e "\n==============================\n"

