name: Python Linting
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Example Interactive Inputs Step
        id: interactive-inputs
        uses: boasihq/interactive-inputs@v2
        with:
          ngrok-authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
          interactive: |
            fields:
              - label: country-rate-limit # Required
                  properties:
                    display: Which country should have a limited request rate? # Optional
                    type: select # Required
                    description: The country that should have requests for unregistered users rate limited # Optional
                    required: false # Optional
                    disableAutoCopySelection: false # Optional: If set to `true`, the user's selected choice will not be automatically copied to the clipboard.
                    choices: # Required: This is the list of options the user can select. It can be generated by a previous step or a static list of options.
                      - US
                      - UK
                      - DE
                      - FR
                      - JP
